### ISSUE TITLE
[feature request] get/set named region(s) on workbook object

### ISSUE THREAD

**Issue by r2evans** [awalker89/openxlsx#118]
There exists `getNamedRegion`, which operates on a workbook *filename*. Is it possible to be able to work on the workbook *object*, and not only retrieve an already-existing name but to define new ones?

Use case: I am using *R* for a lot of data-management, ultimately putting forms of summay data into a spreadsheet as part of a larger decision support system. This process almost always includes data tables and static images, but they also almost always have a "config" worksheet where specific scalar or small-vector user-defined constants are provided. These user-defined constants are typically referred through the spreadsheet by name, not by cell.

As it stands, I am reliant on a pre-existing template with defined (but empty) named ranges. This is certainly manageable, but seems a little silly given the strength `openxlsx` gives to data management in *R*. (Not to mention its stability when compared to `xlsx` and other `rJava`-depending packages.)

Thanks!

**Comment by awalker89** [comment]
0e373c89da90ae6a6ceba7131f18541aed925aa3 adds this functionality.
See
```
?createNamedRegion
?getNamedRegions

## and 'name' argument in 
?writeData
```

**Comment by r2evans** [comment]
Many thanks! I'm checking it out now ...

**Comment by GeraldCNelson** [comment]
I’m having trouble getting a hyperlink to another worksheet in a workbook. The attached workbook is the current output from my R script. The first worksheet is supposed to provide links to the others. 

I write a series of rows into a two column data frame, wbInfo. An example is below. Then I set the class of the first column to ‘hyperlink’ and write it to the workbook. The results, in the first worksheet, are in fact hyperlinks, but they don’t link to the relevant worksheet. Is there an example somewhere of how to construct an internal hyperlink?

Thanks,

Jerry

wbInfo[(nrow(wbInfo)+1),] <- c("=HYPERLINK(metadataFoodCommods!A1,\"metadataFoodCommods\")", "Metadata on commodities and their nutrient makeup.")



Gerald C. Nelson

Professor Emeritus, UIUC

+1 217-390-7888 (cell)

+1 970-639-2079 (land line)

http://bit.ly/1arho7d





From:  Alex
Reply-To:  awalker89/openxlsx
Date:  Sunday, August 16, 2015 at 4:41 AM
To:  awalker89/openxlsx
Subject:  Re: [openxlsx] [feature request] get/set named region(s) on workbook object (#118)


0e373c8 adds this functionality.
See
?createNamedRegion
?getNamedRegions

## and 'name' argument in 
?writeData

**Comment by awalker89** [comment]
Hi Jerry,

It appears you need quotes around the sheet name and also a hash infront.

http://superuser.com/questions/163919/hyperlink-to-other-worksheet-using-hyperlink-function-in-excel


This will work but I think it's a bit messy and the hyperlinks don't show
up blue. I'll write a new function to make this simpler in the future.

Let me know if this works for you,
Alex

require("openxlsx")
wb <- createWorkbook()
addWorksheet(wb, "Sheet1")
addWorksheet(wb, "Sheet2")

writeFormula(wb, "Sheet1", x = 'HYPERLINK("Sheet2!B3", "No Hash")',
startRow = 1) ## does not work
writeFormula(wb, "Sheet1", x = 'HYPERLINK("#Sheet2!B3", "Hash")', startRow
= 2) ## this works

writeData(wb, "Sheet1", x = '=HYPERLINK("Sheet2!B3", "No Hash")', startRow
= 6) ## does not work
writeData(wb, "Sheet1", x = '=HYPERLINK("#Sheet2!B3", "Hash")', startRow =
7) ## this works

openXL(wb)

**Comment by GeraldCNelson** [comment]
Alex, Just getting back to this. 

Before I try your code I thought I’d try to construct a hyperlink to another cell by hand in a worksheet. What a pain! I had to struggle to make this work. The issue seems to be how to tell the link to look in the same worksheet. 

Here’s what finally worked for me manually in a spreadsheet with a worksheet called metadataRegions.

=HYPERLINK("#'metadataRegions'!A1",”test")

Note the location of the double and single quotes. 

Writing a script that does this is ‘challenging’. Haven’t succeeded yet.


Gerald C. Nelson

Professor Emeritus, UIUC

+1 217-390-7888 (cell)

+1 970-639-2079 (land line)

http://bit.ly/1arho7d





From:  Alex
Reply-To:  awalker89/openxlsx
Date:  Thursday, August 20, 2015 at 5:09 PM
To:  awalker89/openxlsx
Cc:  Gerald Nelson
Subject:  Re: [openxlsx] [feature request] get/set named region(s) on workbook object (#118)

Hi Jerry,

It appears you need quotes around the sheet name and also a hash infront.

http://superuser.com/questions/163919/hyperlink-to-other-worksheet-using-hyperlink-function-in-excel


This will work but I think it's a bit messy and the hyperlinks don't show
up blue. I'll write a new function to make this simpler in the future.

Let me know if this works for you,
Alex

require("openxlsx")
wb <- createWorkbook()
addWorksheet(wb, "Sheet1")
addWorksheet(wb, "Sheet2")

writeFormula(wb, "Sheet1", x = 'HYPERLINK("Sheet2!B3", "No Hash")',
startRow = 1) ## does not work
writeFormula(wb, "Sheet1", x = 'HYPERLINK("#Sheet2!B3", "Hash")', startRow
= 2) ## this works

writeData(wb, "Sheet1", x = '=HYPERLINK("Sheet2!B3", "No Hash")', startRow
= 6) ## does not work
writeData(wb, "Sheet1", x = '=HYPERLINK("#Sheet2!B3", "Hash")', startRow =
7) ## this works

openXL(wb)

**Comment by GeraldCNelson** [comment]
Here’s what I have come up with

A function that generates the right excel code
f.hyperlink <- function(sheetName,shtDesc) {
  
  #here's what I need tmp to look like =HYPERLINK("#'metadataRegions'!A1","test")
  part1 <- '=HYPERLINK("#'
  part2 <- paste("'",sheetName,"'",'!A1","',shtDesc,'")', sep = "")
  tmp <- paste(part1, part2, sep="")
}


2. A df called wbInfo that has two columns. Column 1 is for the hyperlinks, column 1 is for some description.



The first column is converted to hyperlink class with

class(wbInfo$sheet_Name) <- ‘hyperlink'



When I run the script, the structure of the hyperlink in the worksheet is correct. When I click on it, it gives me an error. But when I copy the formula and paste it into another cell, it works fine. 



So I’m not sure what is going on, but maybe it has something to doing with the conversion to a hyperlink class and how it is passed to the spreadsheet?

Regards,

Jerry



Gerald C. Nelson

Professor Emeritus, UIUC

+1 217-390-7888 (cell)

+1 970-639-2079 (land line)

http://bit.ly/1arho7d





From:  Gerald Nelson
Date:  Monday, September 14, 2015 at 12:08 PM
To:  awalker89/openxlsx
Subject:  Re: [openxlsx] [feature request] get/set named region(s) on workbook object (#118)

Alex, Just getting back to this. 

Before I try your code I thought I’d try to construct a hyperlink to another cell by hand in a worksheet. What a pain! I had to struggle to make this work. The issue seems to be how to tell the link to look in the same worksheet. 

Here’s what finally worked for me manually in a spreadsheet with a worksheet called metadataRegions.

=HYPERLINK("#'metadataRegions'!A1",”test")

Note the location of the double and single quotes. 

Writing a script that does this is ‘challenging’. Haven’t succeeded yet.


Gerald C. Nelson

Professor Emeritus, UIUC

+1 217-390-7888 (cell)

+1 970-639-2079 (land line)

http://bit.ly/1arho7d





From:  Alex
Reply-To:  awalker89/openxlsx
Date:  Thursday, August 20, 2015 at 5:09 PM
To:  awalker89/openxlsx
Cc:  Gerald Nelson
Subject:  Re: [openxlsx] [feature request] get/set named region(s) on workbook object (#118)

Hi Jerry,

It appears you need quotes around the sheet name and also a hash infront.

http://superuser.com/questions/163919/hyperlink-to-other-worksheet-using-hyperlink-function-in-excel


This will work but I think it's a bit messy and the hyperlinks don't show
up blue. I'll write a new function to make this simpler in the future.

Let me know if this works for you,
Alex

require("openxlsx")
wb <- createWorkbook()
addWorksheet(wb, "Sheet1")
addWorksheet(wb, "Sheet2")

writeFormula(wb, "Sheet1", x = 'HYPERLINK("Sheet2!B3", "No Hash")',
startRow = 1) ## does not work
writeFormula(wb, "Sheet1", x = 'HYPERLINK("#Sheet2!B3", "Hash")', startRow
= 2) ## this works

writeData(wb, "Sheet1", x = '=HYPERLINK("Sheet2!B3", "No Hash")', startRow
= 6) ## does not work
writeData(wb, "Sheet1", x = '=HYPERLINK("#Sheet2!B3", "Hash")', startRow =
7) ## this works

openXL(wb)
