### ISSUE TITLE
addFilter documentation does not match function arguments (version 2.2.1)

### ISSUE THREAD

**Issue by kbeid81** [awalker89/openxlsx#66]
The documentation for addFilter specifies the arguments as wb, sheet, **rows**, cols, and the detail of the arguments for **rows** is "A row numbers".

The argument expected by addFilter is **row** and refers to the row at which the filter is to be added.

I note that there is now a withFilter argument for the writeData function, although the versatility afforded by addFilter can't be overstated :) however the withFilter documentation is mixed up with the borderStyle documentation in the writeData help page.

**Comment by awalker89** [comment]
The argument expected by addFilter is **rows**. It is only a single row buit to keep consistent with other functions it's rows and because R matches parameters row works just fine.

I've updated the documentation to "A row number".

The borderStyle documentation has been fixed in the dev version on github.

Thanks.
