### ISSUE TITLE
Strange converting of cells when importing mixed type columns

### ISSUE THREAD

**Issue by akaever** [awalker89/openxlsx#97]
When importing xlsx files with mixed columns (date and text, number and text), the values are converted strangely. E.g. the column 

12/9/2013
12/17/2013
12/17/2013
string
12/17/2013

is imported (read.xlsx(detectDates=TRUE)) as characters 

41617
41625
41625
string
41625

This also happens, when converting dates to text within Excel (2010). 

When importing a column of numbers mixed with strings, the numbers are converted to strings but with different precision:

7.6
8.4
string
8.5
9.6
9.3

becomes

7.6
8.4
string
8.5
9.6
9.3000000000000007

This also happens when converting the cells to text within Excel before exporting.

Would it be possible to import all columns as characters (as displayed in Excel)? Similar to exporting from Excel as CSV and importing but without loosing additional information (e.g. multiple sheets). 

Thanks

**Comment by awalker89** [comment]
* Excel stored dates internally as the number of days from 1900-01-01 (or 1904-01-01 on mac). 
* columns in R data.frames can only have 1 class.  

Example 1
openxlsx looks to see if it can convert the column to class "Date", sees the "string" and decides it can't without turning "string" in to a date type NA, so returns as is.


Using convertToDate() you can do something like
```
d <- c("41617", "41625", "41625", "string", "41625")
tmp <- convertToDate(d)
d[!is.na(tmp)] <- as.character(tmp[!is.na(tmp)])
> d
[1] "2013-12-09" "2013-12-17" "2013-12-17" "string"     "2013-12-17"
```


Example 2
openxlsx tries to convert the column to numeric but sees "string" and decides it can't.  The precision is not changing, only the number of digits you can see, because it returns a character you see all the digits.

**Comment by akaever** [comment]
That seems to be mainly an Excel issue. But it would be useful if the date-to-string conversion could be done automatically. E.g. if Excel reports type Date for a column which also contains strings, the dates could be converted into human-readable strings (as shown in your example). This is also what seems to happen in the corresponding XLConnect functions.

In the second example, Excel reports the last numeric value as exactly 9.3 (independent of the number of shown digits). But the conversion to 9.3000000000000007 is still most likely an Excel bug. Would it be possible to specify a general precision (number of digits) parameter for numeric-string conversion?

Speaking of number conversion, is there a way to control the conversion of Inf and -Inf in numeric columns when using the openxlsx::saveWorkbook function? Excel reports them as #NUM!

Thanks

**Comment by awalker89** [comment]
I've pushed an update to do the date conversion

![image](https://cloud.githubusercontent.com/assets/7400673/8694920/8b382ce2-2b25-11e5-8bea-ed36ed90584d.png)

I'll look into the others soon.
